name: Build a firmware

on:

  workflow_call:
    inputs:
      qmk_version:
        default: '0.31.8'
        type: string
        required: false
      keyboard:
        type: string
        required: true
      keymap:
        type: string
        required: true

jobs:

  build:

    name: Build a firmware ${{ inputs.keyboard }}:${{ inputs.keymap }}

    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/qmk/qmk_cli:latest

    env:
      QMK_HOME: ${{ github.workspace }}/__qmk__

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Checkout qmk_firmware
      uses: ./.github/actions/checkout-qmk_firmware
      with:
        version: ${{ inputs.qmk_version }}

    - name: Copy keyboard source
      run: cp -r qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - name: Debug - List keyboard directory
      run: |
        ls -la __qmk__/keyboards/keyball/
        ls -la __qmk__/keyboards/keyball/keyball39/
        qmk config || true

    - name: Install missing python modules
      run: python3 -m pip install --break-system-packages -r __qmk__/requirements.txt

    - name: Compile and link
      run: qmk compile -j 4 -kb keyball/${{ inputs.keyboard }} -km ${{ inputs.keymap }}

    - name: Archive built firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.keyboard }}-${{ inputs.keymap }}-firmware
        path: __qmk__/*.hex
